### ISSUE TITLE
New License Input field Error

### ISSUE THREAD

**Issue by VPBelo** [centralizedinc/fda-client-portal#5]
**Issue:** No close button/ Back button and Fix UI for general information in additional activity chips selected no close per data.
-Landline, Fax and mobile number should be masked in Contact Information.
-No digit limit in ID Number in Government Issued identification document.
**Module:** New License
![c](https://user-images.githubusercontent.com/34052250/54413028-6977ba80-472f-11e9-986d-ed662e4ae201.PNG)
![f](https://user-images.githubusercontent.com/34052250/54413030-6977ba80-472f-11e9-97e9-d1f79af0102e.PNG)
![y](https://user-images.githubusercontent.com/34052250/54413033-6a105100-472f-11e9-9e7b-decb20b7e6cd.PNG)

**Comment by fqui8** [comment]
**- Deployment version 0.1.16**
**- File path: fda-client-portal/src/views/app/licenses/create**

**- Resolution:**
- [ ] Phone/Fax number masked to 10-digit numbering format including area code.
- [ ] Mobile number masked to 11-digit numbering format.
- [ ] ID Number cannot be masked due to different counts of ID Number depending on the ID Type
- [ ] Icon displayed for next and previous button
![Screen Shot 2019-03-18 at 1 59 06 PM](https://user-images.githubusercontent.com/36065227/54509871-0e8bd080-4986-11e9-8334-e4d3cc4c579c.png)
