### ISSUE TITLE
Change password error

### ISSUE THREAD

**Issue by VPBelo** [centralizedinc/fda-client-portal#8]
**Issue**: Did not save any changes for changing password.
-Fixing of submit button is big.
**Module**: Password Settings

Expected Result:
Can type/edit client

Actual Result:
Failed, User cannot login using new password.
![eeee](https://user-images.githubusercontent.com/34052250/54415801-6208df00-4738-11e9-8b3a-b6a5e3361d19.PNG)
![iiiiii](https://user-images.githubusercontent.com/34052250/54415865-9e3c3f80-4738-11e9-99b9-a04978b10c63.PNG)

**Comment by mquijom** [comment]
Deployment Version: **0.1.21**

Files: 
- **fda-client-portal/views/app/passwordSettings/ChangePassword.vue**
- **fda-client-portal/views/app/passwordSettings/ResetPassword.vue**
- **fda-client-portal/store/modules/user_session.js**
- **fda-client-portal/api/PasswordAPI.js**
- **fda-services-accounts/api/routes/accounts_router.js**
- **fda-services-notifications/api/routes/notifications_router.js**

Remarks
Fixed by implementing new design and architecture of Password Reset

![image](https://user-images.githubusercontent.com/34019450/54813475-97797380-4cc8-11e9-94ba-e597ce65877c.png)

![image](https://user-images.githubusercontent.com/34019450/54812899-39985c00-4cc7-11e9-85b2-1e6ca7012d71.png)

**Comment by kyango** [comment]
Closing Issue

**Comment by fqui8** [comment]
Back to home (closing issue) after password reset fixed
